config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :questions do
    resources :answers, except: [:new, :index, :show]
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:destroy, :create]
  end

  get '/trending' => 'questions#trending'
  get '/votes' => 'questions#votes'
  get '/recent' => 'questions#index'
  get '/search' => 'questions#search'

  resources :answers, only: [:show] do
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:destroy, :create]
  end

  resources :users, except: [:index, :show, :new]
  get '/register' => 'users#new'
  get '/profile/:id' => 'users#show', as: 'profile'

end

app/models/question.rb
class Question < ActiveRecord::Base

	validates_presence_of :content, :title
	validates :title, length: {maximum: 150}
	validates :content, length: {maximum: 5000}

	belongs_to :submitter, class_name: :User
	has_many :answers
	has_many :comments, as: :commentable
	has_many :votes, as: :voteable

	def rating
		votes.pluck(:value).reduce(:+) || 0
	end

	def has_best_answer?
		best_answer_id
	end	

	def votes_per_hour
		votes.select {|vote| vote.created_at < 1.hour.ago}.count
	end

	def self.order_by_recent
		self.order(created_at: :desc)
	end

	def self.order_by_trending
		self.all.sort {|q1, q2| q2.votes_per_hour <=> q1.votes_per_hour}
	end

	def self.order_by_votes
		self.all.sort {|q1, q2| q2.rating <=> q1.rating}
	end

	def timestamp
		milliseconds = self.created_at.to_i/1000
		seconds = milliseconds/1000
		minutes = seconds/60
		hours = minutes/60
		days = hours/24

		if minutes == 0
			return "#{seconds} seconds"
		elsif hours == 0
			return "#{minutes} minutes"
		elsif days == 0
			return "#{hours} hours"
		else
			return "#{days} days"
		end
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    @question = Question.new
    @questions = Question.order_by_recent
  end

  def trending
    @questions = Question.order_by_trending
    render :index
  end

  def votes
    @questions = Question.order_by_votes
    render :index
  end

  def search
    @questions = Question.where("title ILIKE ?", "%#{params[:search]}%")
    @questions.order_by_recent
    render :index
  end

  def show
    @comments = @question.comments
    @answers = @question.answers.includes(:comments)
    @vote = Vote.new
    @answer = Answer.new
    @comment = Comment.new
  end

  def new
    @question = Question.new
  end

  def create
    question = Question.new(question_params.merge(submitter: current_user))
    if question.save
      redirect_to question_path(question)
    else
      redirect_to new_question_path, flash: {error: "Invalid input: must include both title and content."}
    end
  end

  def edit
  end

  def update
    if @question.update_attributes(question_params)
      redirect_to question_path(@question)
    else
      redirect_to edit_question_path(@question), flash: {error: "Invalid input: must include both title and content." }
    end
  end

  def destroy
    @question.destroy
    redirect_to root_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :content)
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def authenticate_user
    redirect_to root_path if !current_user
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  Title: <%= f.text_field :title %><br>
  <%= f.text_area :content %><br>
  <%= f.submit "Submit" %>
<% end %>

app/views/questions/_question.html.erb
<h1><%= question.title %></h1>
<table>
  <tr>
    <td>
      <% if logged_in? && current_user.posted_question?(question) %>
        <%= link_to "Edit Question", edit_question_path %>
        <%= link_to "Delete Question", question_path(question), method: :delete %>
      <% end %>

      <% if logged_in? && current_user.authorized_to_vote_on_question?(question) %>
        <div class='upvote'>
          <%= form_for @vote, url: question_votes_path(question) do |f| %>
            <%= f.hidden_field :value, value: 1 %>
          	<%= image_submit_tag("up-arrow.png", class: "vote") %>
          <% end %>
        </div>

         <p class="rating"><%=question.rating%> votes</p>

        <div class='downvote'>
        	<%= form_for @vote, url: question_votes_path(question) do |f| %>
        	<%= f.hidden_field :value, value: -1 %>
        	<%= image_submit_tag("down-arrow.png", class: "vote") %>
        	<% end %>
        </div>
      <% else %>

    <div class="vote-buttons">
        <%= link_to image_tag("up-arrow.png"), class: "vote" %>
        <div class="rating"><%=question.rating%> votes</div>
        <%= link_to image_tag("down-arrow.png"), class: "vote" %>
      <% end %>
     </div>
    </td>
    <td>
      <p class="question-content"><%= question.content %></p>
    </td>
  </tr>
</table>

<div class="submitter">
  <%= image_tag question.submitter.avatar_url, class: "icon" %>
  <%= link_to question.submitter.username, profile_path(question.submitter) %><br>
  asked <%= question.timestamp %> ago
</div>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1 class="q-header title">Questions</h1>

<nav class="question-links">
	<%= link_to "Recent", recent_path, class: "sub-button" %>
	<%= link_to "Popular", votes_path, class: "sub-button" %>
	<%= link_to "Trending", trending_path, class: "sub-button" %>
</nav>

<hr>

<% if @questions.empty? %>
  <p>There are no questions that match your search.<br>
    Your search query might be too specific.</p>
<% end %>

<% @questions.each do |question| %>
<table>
	<tr>
		<td class="q-stats">
      <%= question.answers.count %><br>
      answers
		</td>
    <td class="q-stats">
      <%= question.rating %><br>
      votes
    </td>
		<td class="q-info">
			<p class="q-title"><%= link_to question.title, question_path(question) %></p>
			<p><%= question.content %></p>
			<sub>asked <%= question.timestamp %> ago <%= link_to "#{question.submitter.username}", profile_path(question.submitter) %></sub>
		</td>
	</tr>
</table>
<hr>
<% end %>

app/views/questions/new.html.erb
<h1>Ask a Question</h1>

<%= flash[:error] %>

<%= render "form" %>

app/views/questions/show.html.erb
<main>
  <%= render @question %>

  <ul class="question-comments-list">
    <%= render @comments %>
  </ul>

  <% if logged_in? %>
    <%= render partial:"comments/new", object: @comment %>
  <% end %>

  <div class="answers">
    <h2 class="subtitle"><%= @question.answers.count %> Answers</h2>
    <hr>
    <%= render @answers %>
  </div>

  <% if logged_in? %>
    <%= render partial:"answers/new", object: @answer %>
  <% end %>
</main>