config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :questions do
    resources :answers, except: [:new, :index, :show]
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:destroy, :create]
  end

  get '/trending' => 'questions#trending'
  get '/votes' => 'questions#votes'
  get '/recent' => 'questions#index'
  get '/search' => 'questions#search'

  resources :answers, only: [:show] do
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:destroy, :create]
  end

  resources :users, except: [:index, :show, :new]
  get '/register' => 'users#new'
  get '/profile/:id' => 'users#show', as: 'profile'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates_presence_of :content
	validates :content, length: {maximum: 1500}

	belongs_to :commentable, polymorphic: true
	belongs_to :commentator, class_name: :User
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user

  def create
    if params[:answer_id]
      answer = Answer.find_by(id: params[:answer_id])
      @question = answer.question
      @comment = answer.comments.build(comment_params.merge(commentator: current_user))
      if @comment.save && request.xhr?
        render @comment
      else
        redirect_to question_path(@question), flash: {error: "Comment must be 1500 chars or less." }
      end
    elsif params[:question_id]
      @question = Question.find_by(id: params[:question_id])
      @comment = @question.comments.build(comment_params.merge(commentator: current_user))
      if @comment.save && request.xhr?
        render @comment
      else
        redirect_to question_path(@question), flash: {error: "Comment must be 1500 chars or less." }
      end
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    if params[:question_id]
      @question = Question.find_by(id: params[:question_id])
    elsif params[:answer_id]
      @question = Answer.find_by(id: params[:answer_id]).question
    end
    comment.destroy
    redirect_to question_path(@question)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def authenticate_user
    redirect_to root_path if !current_user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_answer_comment.html.erb
<li>
  <%= link_to comment.commentator.username, profile_path(comment.commentator) %>: <%=comment.content%>
</li>

<% if logged_in? && current_user.posted_comment?(comment) %>
	<li><%=form_for comment, url: answer_comment_path(answer, comment) do |f| %>
		<%= hidden_field_tag("_method", "delete") %>
		<%= f.submit "Delete comment" %>
		<% end %>
	</li>
<% end %>

app/views/comments/_answer_new.html.erb
<%= form_for @comment, url: answer_comments_path(answer), html: {id: "answer-comment-form"} do |f| %>
	<%= text_area(:comment, :content, cols: 30, rows: 5) %><br>
	<%= f.submit "Add comment" %>
<% end %>

app/views/comments/_comment.html.erb
<li>
    <%= link_to comment.commentator.username, profile_path(comment.commentator) %>: <%=comment.content%>
    <% if logged_in? && current_user.posted_comment?(comment) %>
      <%= form_for comment, url: question_comment_path(@question, comment) do |f| %>
        <%= hidden_field_tag("_method", "delete") %>
        <%= f.submit "Delete comment" %>
      <% end %>
    <% end %>
</li>

app/views/comments/_new.html.erb
<%= form_for @comment, url: question_comments_path(@question) do |f| %>
	<%= text_area(:comment, :content, cols: 30, rows: 5) %>
	<%= f.submit "Add comment" %>
<% end %>