config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :questions do
    resources :answers, except: [:new, :index, :show]
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:destroy, :create]
  end

  get '/trending' => 'questions#trending'
  get '/votes' => 'questions#votes'
  get '/recent' => 'questions#index'
  get '/search' => 'questions#search'

  resources :answers, only: [:show] do
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:destroy, :create]
  end

  resources :users, except: [:index, :show, :new]
  get '/register' => 'users#new'
  get '/profile/:id' => 'users#show', as: 'profile'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	validates_presence_of :content
	validates :content, length: {maximum: 2000}

	has_many :comments, as: :commentable
	has_many :votes, as: :voteable
	belongs_to :responder, class_name: :User
	belongs_to :question

	def rating
		votes.pluck(:value).reduce(:+) || 0
	end

  def timestamp
    milliseconds = self.created_at.to_i/1000
    seconds = milliseconds/1000
    minutes = seconds/60
    hours = minutes/60
    days = hours/24

    if minutes == 0
      return "#{seconds} seconds"
    elsif hours == 0
      return "#{minutes} minutes"
    elsif days == 0
      return "#{hours} hours"
    else
      return "#{days} days"
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	before_action :authenticate_user
	before_action :find_answer, :find_question, except: [:create]
	before_action :authorize_user, only: [:edit]

	def create
		@question = Question.find_by(id: params[:question_id])
		answer = @question.answers.build(answer_params.merge(responder: current_user))
		if answer.save
			redirect_to question_path(@question)
		else
		redirect_to question_path(@question), flash: {error: 'Failed to Submit the Answer!'}
		end
	end

	def edit
	end

	def update
		@question.update_attributes(best_answer_id: @answer.id) if params[:answer][:best_answer]
		if @answer.update_attributes(answer_params)
			redirect_to question_path(@question)
		else
			redirect_to question_path(@question), flash: {error: 'Failed to Update the Answer!'}
		end
	end

	def destroy
		@answer.destroy
		redirect_to question_path(@question)
	end

	private

	def find_answer
		@answer = Answer.find_by(id: params[:id])
	end

	def find_question
		@question = @answer.question
	end

	def answer_params
		params.require(:answer).permit(:content, :best_answer)
	end

	def authenticate_user
		redirect_to question_path(@question) if !current_user
	end

	def authorize_user
		redirect_to question_path(@question) if current_user!=@answer.responder
	end
end

app/views/answers/_answer.html.erb
<table>
  <tr>
    <td>
      <% if logged_in? && current_user.authorized_to_vote_on_answer?(answer)%>
      <div class="upvote">
        <%=form_for @vote, url: answer_votes_path(answer) do |f| %>
        <%= f.hidden_field :value, value: 1 %>
        <%= image_submit_tag("up-arrow.png", class: "answer-vote") %>
        <%end%>
      </div>
      <div class="center"><%= answer.rating %></div>
      <div class='downvote'>
        <%=form_for @vote, url: answer_votes_path(answer) do |f| %>
          <%= f.hidden_field :value, value: -1 %>
          <%= image_submit_tag("down-arrow.png", class: "answer-vote") %>
        <%end%>
      </div>
      <% else %>
      <div class="answer-vote-buttons">
        <%= link_to image_tag("up-arrow.png"), class: "answer-vote" %>
        <div class="center"><%= answer.rating %></div>
        <%= link_to image_tag("down-arrow.png"), class: "answer-vote" %>
        <% end %>
      </div>
    </td>
    <td>
      <% if answer.best_answer %>
        <p>Chosen as best answer!</p>
      <% end %>

      <%= link_to answer.responder.username, profile_path(answer.responder) %>: <%=answer.content %>
    </td>
  </tr>
</table>

<% if logged_in? && current_user.posted_question?(@question) && !@question.has_best_answer?%>
  <div class="choose-best-answer">
    <%= form_for answer, url: question_answer_path(@question, answer) do |f| %>
      <%= hidden_field_tag("_method", "put") %>
      <%= f.hidden_field :best_answer, value: true %>
      <%= f.submit "Choose as best answer" %>
    <% end %>
  </div>
<% end %>

<% if logged_in? && current_user.posted_answer?(answer) %>
  <div class="answer-edit">
    <%= link_to "Edit answer", edit_question_answer_path(@question, answer) %>
  </div>
  <div class="answer-delete">
    <%=form_for answer, url: question_answer_path(@question, answer) do |f| %>
      <%= hidden_field_tag("_method", "delete") %>
      <%= f.submit 'Delete answer' %>
    <%end%>
  </div>
<%end%>

<ul class="answer-comments-list">
  <%= render partial:"comments/answer_comment", collection:answer.comments, as: :comment, locals: {answer: answer} %>
  <% if logged_in? %>
    <%= render partial:"comments/answer_new", object: @comment, locals: {answer: answer} %>
  <% end %>
</ul>
<hr>

app/views/answers/_new.html.erb
<div class="new-answer">
	<h3 class="subtitle"> Submit an answer </h3>
	<%= form_for @answer, url: question_answers_path(@question), html: {id: "answer-comment-form"} do |f| %>
  	<%= text_area(:answer, :content, cols: 30, rows: 10) %>
  	<%= f.submit "Add answer" %>
	<% end %>
</div>

app/views/answers/edit.html.erb
<h1>Edit your answer to "<%=@question.title%>"</h1>

<%= form_for @answer, url: question_answer_path(@question, @answer) do |f| %>
	<%= hidden_field_tag("_method", "put") %>
	<%= text_area(:answer, :content, cols: 30, rows: 10) %>
	<%= f.submit "Edit answer" %>
<% end %>	