config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :questions do
    resources :answers, except: [:new, :index, :show]
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:destroy, :create]
  end

  get '/trending' => 'questions#trending'
  get '/votes' => 'questions#votes'
  get '/recent' => 'questions#index'
  get '/search' => 'questions#search'

  resources :answers, only: [:show] do
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:destroy, :create]
  end

  resources :users, except: [:index, :show, :new]
  get '/register' => 'users#new'
  get '/profile/:id' => 'users#show', as: 'profile'

end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<%end%>

<%if flash[:error] %>
  <%= flash[:error]%>
<%end%>

<% if flash[:registration_error] %>
  <% flash[:registration_error].each do |error| %>
    <li><%= error %></li>
  <%end%>
<%end%>

app/views/layouts/_footer.html.erb
<footer>
  <p>Designed by Team Baconator & French Fries. Yum.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="logo">
    <%= link_to root_path do %>
      <div id="so-img"><%=image_tag("so-icon.png") %></div>
      <div id="word-1"><%=image_tag("logo-word-1.png")%></div>
      <div id="word-2"><%=image_tag("logo-word-2.png") %></div>
    <% end %>
  </div>
  <nav class="header-nav">
    <%= link_to "Questions", root_path %>
    <% if logged_in? %>
      <%= link_to "Ask a Question", new_question_path %>
      <%= link_to "Profile", profile_path(current_user) %>
      <%= link_to "Log Out", logout_path, method: :delete %>
    <%else%>
      <%= link_to "Sign Up", register_path, class: "button" %>
      <%= link_to "Log In", login_path, class: "button" %>
    <%end%>
    <p>
      <%= form_for :question, url: search_path, method: "get", id: "search" do |f|%>
        <%= image_tag("searchicon.png") %>
        <%= f.text_field :title, name: "search", placeholder: "search", class: "search-text", value: "" %>
      <% end %>
    <p>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JacquesOverflow</title>
  <link href='https://fonts.googleapis.com/css?family=Oswald|Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'french-flag.ico' %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="content">
  	<%= render "layouts/flash" %>
  	<%= yield %>
	</div>
  <%= render "layouts/footer" %>
</body>
</html>